[context.production.environment]
NEXT_PUBLIC_GOOGLE_ANALYTICS_ID = "G-6CPN4DELXW"

[[headers]]
  for = "/nextimg/*"
  [headers.values]
  cache-control = '''
  public,
  max-age=604800,
  stale-while-revalidate=86400
  '''

[[redirects]]
  from = "/cv"
  to = "/cv.pdf"
  status = 301
  force = true

